prompt --install
@@apex/application/set_environment.sql
@@apex/application/delete_application.sql
@@apex/application/create_application.sql
@@apex/application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@apex/application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@apex/application/shared_components/navigation/lists/desktop_tasks_cards.sql
@@apex/application/plugin_settings.sql
@@apex/application/shared_components/navigation/navigation_bar.sql
@@apex/application/shared_components/logic/application_settings.sql
@@apex/application/shared_components/navigation/tabs/standard.sql
@@apex/application/shared_components/navigation/tabs/parent.sql
@@apex/application/shared_components/user_interface/lovs/yes_no.sql
@@apex/application/pages/page_groups.sql
@@apex/application/comments.sql
@@apex/application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@apex/application/shared_components/navigation/breadcrumbentry.sql
@@apex/application/shared_components/user_interface/templates/page/drawer.sql
@@apex/application/shared_components/user_interface/templates/page/left_side_column.sql
@@apex/application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@apex/application/shared_components/user_interface/templates/page/login.sql
@@apex/application/shared_components/user_interface/templates/page/master_detail.sql
@@apex/application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@apex/application/shared_components/user_interface/templates/page/modal_dialog.sql
@@apex/application/shared_components/user_interface/templates/page/right_side_column.sql
@@apex/application/shared_components/user_interface/templates/page/standard.sql
@@apex/application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@apex/application/shared_components/user_interface/templates/button/icon.sql
@@apex/application/shared_components/user_interface/templates/button/text.sql
@@apex/application/shared_components/user_interface/templates/button/text_with_icon.sql
@@apex/application/shared_components/user_interface/templates/region/inline_drawer.sql
@@apex/application/shared_components/user_interface/templates/region/image.sql
@@apex/application/shared_components/user_interface/templates/region/inline_popup.sql
@@apex/application/shared_components/user_interface/templates/region/cards_container.sql
@@apex/application/shared_components/user_interface/templates/region/alert.sql
@@apex/application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@apex/application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@apex/application/shared_components/user_interface/templates/region/buttons_container.sql
@@apex/application/shared_components/user_interface/templates/region/carousel_container.sql
@@apex/application/shared_components/user_interface/templates/region/collapsible.sql
@@apex/application/shared_components/user_interface/templates/region/content_block.sql
@@apex/application/shared_components/user_interface/templates/region/hero.sql
@@apex/application/shared_components/user_interface/templates/region/inline_dialog.sql
@@apex/application/shared_components/user_interface/templates/region/interactive_report.sql
@@apex/application/shared_components/user_interface/templates/region/login.sql
@@apex/application/shared_components/user_interface/templates/region/standard.sql
@@apex/application/shared_components/user_interface/templates/region/tabs_container.sql
@@apex/application/shared_components/user_interface/templates/region/title_bar.sql
@@apex/application/shared_components/user_interface/templates/region/wizard_container.sql
@@apex/application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@apex/application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@apex/application/shared_components/user_interface/templates/list/badge_list.sql
@@apex/application/shared_components/user_interface/templates/list/cards.sql
@@apex/application/shared_components/user_interface/templates/list/links_list.sql
@@apex/application/shared_components/user_interface/templates/list/media_list.sql
@@apex/application/shared_components/user_interface/templates/list/menu_bar.sql
@@apex/application/shared_components/user_interface/templates/list/menu_popup.sql
@@apex/application/shared_components/user_interface/templates/list/navigation_bar.sql
@@apex/application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@apex/application/shared_components/user_interface/templates/list/tabs.sql
@@apex/application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@apex/application/shared_components/user_interface/templates/list/wizard_progress.sql
@@apex/application/shared_components/user_interface/templates/report/content_row.sql
@@apex/application/shared_components/user_interface/templates/report/contextual_info.sql
@@apex/application/shared_components/user_interface/templates/report/media_list.sql
@@apex/application/shared_components/user_interface/templates/report/alerts.sql
@@apex/application/shared_components/user_interface/templates/report/badge_list.sql
@@apex/application/shared_components/user_interface/templates/report/cards.sql
@@apex/application/shared_components/user_interface/templates/report/comments.sql
@@apex/application/shared_components/user_interface/templates/report/search_results.sql
@@apex/application/shared_components/user_interface/templates/report/standard.sql
@@apex/application/shared_components/user_interface/templates/report/timeline.sql
@@apex/application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@apex/application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@apex/application/shared_components/user_interface/templates/label/optional_floating.sql
@@apex/application/shared_components/user_interface/templates/label/required_floating.sql
@@apex/application/shared_components/user_interface/templates/label/hidden.sql
@@apex/application/shared_components/user_interface/templates/label/optional.sql
@@apex/application/shared_components/user_interface/templates/label/optional_above.sql
@@apex/application/shared_components/user_interface/templates/label/required.sql
@@apex/application/shared_components/user_interface/templates/label/required_above.sql
@@apex/application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@apex/application/shared_components/user_interface/templates/popuplov.sql
@@apex/application/shared_components/user_interface/templates/calendar/calendar.sql
@@apex/application/shared_components/user_interface/themes.sql
@@apex/application/shared_components/user_interface/theme_style.sql
@@apex/application/shared_components/user_interface/theme_files.sql
@@apex/application/shared_components/user_interface/template_opt_groups.sql
@@apex/application/shared_components/user_interface/template_options.sql
@@apex/application/shared_components/globalization/language.sql
@@apex/application/shared_components/globalization/translations.sql
@@apex/application/shared_components/logic/build_options.sql
@@apex/application/shared_components/globalization/messages.sql
@@apex/application/shared_components/globalization/dyntranslations.sql
@@apex/application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@apex/application/shared_components/security/authentications/application_express_authentication.sql
@@apex/application/user_interfaces.sql
@@apex/application/user_interfaces/combined_files.sql
@@apex/application/pages/page_00001.sql
@@apex/application/pages/page_00002.sql
@@apex/application/pages/page_00003.sql
@@apex/application/pages/page_00004.sql
@@apex/application/pages/page_00005.sql
@@apex/application/pages/page_00006.sql
@@apex/application/pages/page_00008.sql
@@apex/application/pages/page_00101.sql
@@apex/application/pages/page_10040.sql
@@apex/application/pages/page_10041.sql
@@apex/application/end_environment.sql
