-- drop objects
declare
   l_cnt    pls_integer;
begin
   select count(*) into l_cnt from user_tables where table_name = upper('ht_weight');

   if (l_cnt > 0) then
      execute immediate 'drop table ht_weight cascade constraints purge';
   end if;
end;
/

-- create tables
create table ht_weight (
   id                number generated by default on null as identity
                        constraint ht_weight_id__pk primary key,
   created           timestamp with time zone default current_timestamp not null,
   created_by        varchar2(255 char) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), user) not null,
   weight            number not null,
   bmi               number,
   ignore_flg         varchar2(1 char) default 'N' not null,
   notes             varchar2(4000 char)
)
;

comment on table ht_weight is 'Contains data related to the weight.';
comment on column ht_weight.id is 'Surrogate key.';
comment on column ht_weight.created is 'Date when record was inserted.';
comment on column ht_weight.created_by is 'Who created the record.';
comment on column ht_weight.weight is 'Value of the weight.';
comment on column ht_weight.bmi is 'Calculated BMI value.';
comment on column ht_weight.ignore_flg is 'Indicates, if the row should be ignored.';
comment on column ht_weight.notes is 'Various notes if needed.';
